/* eslint-disable */
// This file is autogenerated by scripts/generate-asyncapi-playground-specs.mjs
import type { PlaygroundSpec } from "./types";

const aqaraLifeWebSocketSpecEn = {
  "title": "Studio WebSocket API",
  "version": "v1",
  "description": "This document describes the asynchronous messages exchanged between the client and the Studio WebSocket service:\n- The client sends authentication, heartbeat, subscribe, and unsubscribe requests.\n- Studio returns responses to requests and proactively pushes messages when subscriptions match or device events occur.\n- WebSocket supports two authentication methods: the handshake header `Authorization: Bearer <accessToken>` and an initial `AuthRequest` message after connection establishment.\n",
  "servers": [
    {
      "id": "remoteAccess",
      "label": "Remote Access",
      "description": "Studio remote-access domain name.",
      "protocol": "wss",
      "hostDefault": "xxx.edge-xxx.aqara.com",
      "pathname": "/open/ws"
    },
    {
      "id": "local",
      "label": "Local / LAN",
      "description": "Studio local-access IP address or host domain name.",
      "protocol": "ws",
      "hostDefault": "xxx.xxx.xxx.xxx",
      "pathname": "/open/ws"
    }
  ],
  "operations": [
    {
      "id": "sendAuthRequest",
      "action": "send",
      "messages": [
        "AuthRequest"
      ]
    },
    {
      "id": "receiveAuthResponse",
      "action": "receive",
      "messages": [
        "AuthResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "sendPing",
      "action": "send",
      "messages": [
        "PingRequest"
      ]
    },
    {
      "id": "receivePong",
      "action": "receive",
      "messages": [
        "PongResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "sendSubscriptionCommand",
      "action": "send",
      "messages": [
        "SubscribeAllRequest",
        "UnsubscribeAllRequest",
        "SubscribeTraitValueRequest",
        "UnsubscribeTraitValueRequest"
      ]
    },
    {
      "id": "receiveSubscriptionCommandResponse",
      "action": "receive",
      "messages": [
        "SubscribeAllResponse",
        "UnsubscribeAllResponse",
        "SubscribeTraitValueResponse",
        "UnsubscribeTraitValueResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "receivePushMessage",
      "action": "receive",
      "messages": [
        "TraitValueUpdate",
        "ObjectEvent",
        "ErrorMessage"
      ]
    }
  ],
  "messages": {
    "AuthRequest": {
      "name": "AuthRequest",
      "title": "WebSocket authentication request",
      "summary": "First-message authentication flow; used when Authorization is not included in the handshake header.",
      "examples": [
        {
          "name": "bearerToken",
          "payload": {
            "type": "AuthRequest",
            "version": "v1",
            "msgId": "10001",
            "data": {
              "authType": "token",
              "token": "Bearer <Token>"
            }
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "AuthRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "object",
            "required": [
              "token"
            ],
            "properties": {
              "authType": {
                "type": "string",
                "description": "Authentication type. Pass `token`.",
                "enum": [
                  "token"
                ],
                "default": "token"
              },
              "token": {
                "type": "string",
                "description": "Use the format `Bearer <Token>`, where `<Token>` is the raw token obtained from Aqara Studio. Do not log or expose this token."
              }
            }
          }
        }
      }
    },
    "AuthResponse": {
      "name": "AuthResponse",
      "title": "WebSocket authentication response",
      "examples": [
        {
          "name": "success",
          "payload": {
            "type": "AuthResponse",
            "version": "v1",
            "msgId": "10001",
            "data": "",
            "code": 0,
            "message": "Authentication successful. Welcome <username>"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "AuthResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "PingRequest": {
      "name": "ping",
      "title": "Heartbeat request",
      "examples": [
        {
          "name": "ping",
          "payload": {
            "type": "ping",
            "version": "v1",
            "msgId": "10002",
            "data": null
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ping"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": null
          }
        }
      }
    },
    "PongResponse": {
      "name": "pong",
      "title": "Heartbeat response",
      "examples": [
        {
          "name": "pong",
          "payload": {
            "type": "pong",
            "version": "v1",
            "msgId": "10002",
            "data": "pong",
            "code": 0,
            "message": "success"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "pong"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "string",
            "enum": [
              "pong"
            ]
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "SubscribeAllRequest": {
      "name": "SubscribeAllRequest",
      "title": "Subscribe to all or selected devices request",
      "examples": [
        {
          "name": "allDevices",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244328",
            "data": null
          }
        },
        {
          "name": "specifiedDevices",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244328",
            "data": [
              "deviceId"
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeAllRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "array",
              "null"
            ],
            "default": null,
            "description": "List of device IDs. When `null` or omitted, it subscribes to all device data within the current permission scope and clears previously established device-level subscriptions.\nWhen `data` is non-empty, the \"subscribe all devices\" state is cancelled and these device-level subscriptions are appended, but any other previously appended device-level subscriptions are not automatically cleared.\nWhen using a restricted API AccessToken, an empty `data` array may return `code=0` without creating an effective subscription; when subscribing to all devices within the authorized scope, it is recommended to pass `null` or omit `data`.\nTo narrow or replace the device-level subscription scope, first use `UnsubscribeAllRequest` to remove devices that are no longer needed.\nTo clear all subscriptions on the current connection, send `UnsubscribeAllRequest` with an empty `data` array or omit `data`.\nIf the current account or token permission scope has no accessible devices, the server may return `code=0` but no subsequent push messages will be generated.\nWithin the same connection, `SubscribeAllRequest` overrides and clears Trait subscriptions previously established via `SubscribeTraitValueRequest`.\nTo switch from all-device or selected-device subscriptions back to Trait-only subscriptions, first send `UnsubscribeAllRequest` to clear the all-device/device-level subscriptions.\n",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "SubscribeAllResponse": {
      "name": "SubscribeAllResponse",
      "title": "Subscribe to all or selected devices response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeAllResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "UnsubscribeAllRequest": {
      "name": "UnsubscribeAllRequest",
      "title": "Unsubscribe from all or selected devices request",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeAllRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "array",
              "null"
            ],
            "default": null,
            "description": "List of device IDs. Empty or `null` means unsubscribe from everything.\nIf the current connection is subscribed to all devices, unsubscribing by specific device IDs has no effect; pass an empty value to cancel all subscriptions.\nWithin the same connection, `UnsubscribeAllRequest` also clears Trait subscriptions previously established via `SubscribeTraitValueRequest`.\nUnsubscribing specific devices only removes device-level subscriptions and does not mean stopping all push messages on the current connection.\n",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "UnsubscribeAllResponse": {
      "name": "UnsubscribeAllResponse",
      "title": "Unsubscribe from all or selected devices response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeAllResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "SubscribeTraitValueRequest": {
      "name": "SubscribeTraitValueRequest",
      "title": "Subscribe to specified Trait values request",
      "examples": [
        {
          "name": "subscribeTrait",
          "payload": {
            "type": "SubscribeTraitValueRequest",
            "version": "v1",
            "msgId": "get_devices_1751609244328",
            "data": [
              {
                "deviceId": "57190441014857",
                "endpointId": 3,
                "functionCode": "MediaPlayback",
                "traitCodes": [
                  "TargetPlaybackState"
                ]
              }
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeTraitValueRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "description": "List of Traits to subscribe to. A non-empty array is recommended; omitting `data` causes parsing to fail.\nIn the current implementation, an empty array or empty `traitCodes` may still return a success response, but no effective `TraitValueUpdate` subscription will be created.\n",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCodes"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "Device ID."
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "Endpoint ID."
                },
                "functionCode": {
                  "type": "string",
                  "description": "Function code."
                },
                "traitCodes": {
                  "type": "array",
                  "description": "List of Trait feature point codes. A non-empty array is recommended; an empty array does not create or cancel any specific Trait subscriptions, although the current implementation may still return a success response.",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "SubscribeTraitValueResponse": {
      "name": "SubscribeTraitValueResponse",
      "title": "Subscribe to specified Trait values response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeTraitValueResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "UnsubscribeTraitValueRequest": {
      "name": "UnsubscribeTraitValueRequest",
      "title": "Unsubscribe from specified Trait values request",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeTraitValueRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "default": [],
            "description": "List of Traits to unsubscribe from. A non-empty array is recommended.\nOmitting `data`, passing an empty array, or using empty `traitCodes` will not cancel any Trait subscriptions, although the current implementation may still return a success response.\n",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCodes"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "Device ID."
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "Endpoint ID."
                },
                "functionCode": {
                  "type": "string",
                  "description": "Function code."
                },
                "traitCodes": {
                  "type": "array",
                  "description": "List of Trait feature point codes. A non-empty array is recommended; an empty array does not create or cancel any specific Trait subscriptions, although the current implementation may still return a success response.",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "UnsubscribeTraitValueResponse": {
      "name": "UnsubscribeTraitValueResponse",
      "title": "Unsubscribe from specified Trait values response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeTraitValueResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "TraitValueUpdate": {
      "name": "TraitValueUpdate",
      "title": "Trait value change push",
      "examples": [
        {
          "name": "traitValueUpdate",
          "payload": {
            "type": "TraitValueUpdate",
            "version": "v1",
            "msgId": "1754469720110",
            "data": [
              {
                "deviceId": "57190441014857",
                "endpointId": 3,
                "functionCode": "MediaPlayback",
                "traitCode": "TargetPlaybackState",
                "value": "0",
                "time": 1754469720110
              }
            ],
            "code": 0,
            "message": ""
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TraitValueUpdate"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCode",
                "time"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "Device ID."
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "Endpoint ID."
                },
                "functionCode": {
                  "type": "string",
                  "description": "Function code."
                },
                "traitCode": {
                  "type": "string",
                  "description": "Trait feature point code."
                },
                "value": {
                  "description": "Trait feature point value. The actual type is determined by the specific feature point definition."
                },
                "time": {
                  "type": "integer",
                  "format": "int64",
                  "description": "Report timestamp in milliseconds."
                }
              }
            }
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "ObjectEvent": {
      "name": "objectEvent",
      "title": "Object event push",
      "summary": "Object events are pushed at the connection-registration level; the client should dispatch and filter them based on `eventType` and `objectId`.",
      "description": "Object events are pushed according to the current connection's push registration state and are not precisely filtered by `objectId`, device ID, or Trait subscription conditions.\nEven if some subscription requests do not result in an effective `TraitValueUpdate` subscription, the current connection may still receive object events.\nIf the current connection should stop receiving all push messages, send `UnsubscribeAllRequest` with an empty `data` array or omit `data`, or close the WebSocket connection directly.\n",
      "examples": [
        {
          "name": "deviceAdded",
          "payload": {
            "type": "objectEvent",
            "version": "v1",
            "msgId": "2",
            "data": {
              "eventType": "DEVICE_ADDED",
              "objectId": "14d3b91",
              "time": 1754469720110,
              "data": {
                "deviceId": "14d3b91",
                "name": "",
                "deviceTypesList": [
                  "Light"
                ],
                "endpointIds": [
                  0,
                  2,
                  3
                ],
                "time": 1754469720110
              }
            },
            "code": 0,
            "message": "success"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "objectEvent"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "object",
            "required": [
              "eventType",
              "objectId",
              "time"
            ],
            "properties": {
              "eventType": {
                "type": "string",
                "description": "Object event type.",
                "enum": [
                  "DEVICE_ADDED",
                  "DEVICE_REMOVED",
                  "DEVICE_ENDPOINT_ADDED",
                  "DEVICE_ENDPOINT_REMOVED",
                  "DEVICE_TRAIT_PARAMETER_UPDATE"
                ]
              },
              "objectId": {
                "type": "string",
                "description": "Object ID; in device event scenarios, this is typically the device ID."
              },
              "time": {
                "type": "integer",
                "format": "int64",
                "description": "Event timestamp in milliseconds."
              },
              "data": {
                "description": "Concrete structure determined by `eventType`.",
                "type": [
                  "object",
                  "null"
                ],
                "additionalProperties": true
              }
            }
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. `0` indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "ErrorMessage": {
      "name": "ErrorMessage",
      "title": "Error response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ErrorMessage"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Unique message identifier. Normal requests and responses are correlated by the same `msgId`; parse failures, partial-permission issues, or internal errors may return `UNKNOWN`; server push messages are generated by the server and do not correspond to the subscription request `msgId`.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ]
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. Any non-zero value indicates failure; clients are discouraged from relying on specific error codes for fixed business logic decisions."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    }
  }
} satisfies PlaygroundSpec;

export default aqaraLifeWebSocketSpecEn;
