/* eslint-disable */
// This file is autogenerated by scripts/generate-asyncapi-playground-specs.mjs
import type { PlaygroundSpec } from "./types";

const aqaraLifeWebSocketSpecZh = {
  "title": "Studio WebSocket API",
  "version": "v1",
  "description": "本文件描述客户端与 Studio WebSocket 服务之间的异步消息：\n- 客户端发送鉴权、心跳、订阅、取消订阅请求。\n- Studio 返回请求响应，并在订阅命中或设备事件发生时主动推送消息。\n- WebSocket 支持握手 Header `Authorization: Bearer <accessToken>` 与首包 `AuthRequest` 两种认证方式。\n",
  "servers": [
    {
      "id": "remoteAccess",
      "label": "远程访问",
      "description": "Studio 远程访问域名。",
      "protocol": "wss",
      "hostDefault": "xxx.edge-xxx.aqara.cn",
      "pathname": "/open/ws"
    },
    {
      "id": "local",
      "label": "局域网 / 本地",
      "description": "Studio 本地访问 IP 地址或主机访问域名。",
      "protocol": "ws",
      "hostDefault": "xxx.xxx.xxx.xxx",
      "pathname": "/open/ws"
    }
  ],
  "operations": [
    {
      "id": "sendAuthRequest",
      "action": "send",
      "messages": [
        "AuthRequest"
      ]
    },
    {
      "id": "receiveAuthResponse",
      "action": "receive",
      "messages": [
        "AuthResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "sendPing",
      "action": "send",
      "messages": [
        "PingRequest"
      ]
    },
    {
      "id": "receivePong",
      "action": "receive",
      "messages": [
        "PongResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "sendSubscriptionCommand",
      "action": "send",
      "messages": [
        "SubscribeAllRequest",
        "UnsubscribeAllRequest",
        "SubscribeTraitValueRequest",
        "UnsubscribeTraitValueRequest"
      ]
    },
    {
      "id": "receiveSubscriptionCommandResponse",
      "action": "receive",
      "messages": [
        "SubscribeAllResponse",
        "UnsubscribeAllResponse",
        "SubscribeTraitValueResponse",
        "UnsubscribeTraitValueResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "receivePushMessage",
      "action": "receive",
      "messages": [
        "TraitValueUpdate",
        "ObjectEvent",
        "ErrorMessage"
      ]
    }
  ],
  "messages": {
    "AuthRequest": {
      "name": "AuthRequest",
      "title": "WebSocket 鉴权请求",
      "summary": "首包认证方式；未在握手 Header 携带 Authorization 时使用。",
      "examples": [
        {
          "name": "bearerToken",
          "payload": {
            "type": "AuthRequest",
            "version": "v1",
            "msgId": "10001",
            "data": {
              "authType": "token",
              "token": "Bearer <Token>"
            }
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "AuthRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "object",
            "required": [
              "token"
            ],
            "properties": {
              "authType": {
                "type": "string",
                "description": "鉴权方式。请传入 token。",
                "enum": [
                  "token"
                ],
                "default": "token"
              },
              "token": {
                "type": "string",
                "description": "请使用格式：`Bearer <Token>`，其中 `<Token>` 为 Aqara Studio 获取的原始 Token。切勿将此 Token 记录或暴露于日志。"
              }
            }
          }
        }
      }
    },
    "AuthResponse": {
      "name": "AuthResponse",
      "title": "WebSocket 鉴权响应",
      "examples": [
        {
          "name": "success",
          "payload": {
            "type": "AuthResponse",
            "version": "v1",
            "msgId": "10001",
            "data": "",
            "code": 0,
            "message": "Authentication successful. Welcome <username>"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "AuthResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "PingRequest": {
      "name": "ping",
      "title": "心跳请求",
      "examples": [
        {
          "name": "ping",
          "payload": {
            "type": "ping",
            "version": "v1",
            "msgId": "10002",
            "data": null
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ping"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": null
          }
        }
      }
    },
    "PongResponse": {
      "name": "pong",
      "title": "心跳响应",
      "examples": [
        {
          "name": "pong",
          "payload": {
            "type": "pong",
            "version": "v1",
            "msgId": "10002",
            "data": "pong",
            "code": 0,
            "message": "success"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "pong"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "string",
            "enum": [
              "pong"
            ]
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "SubscribeAllRequest": {
      "name": "SubscribeAllRequest",
      "title": "订阅全部/部分设备请求",
      "examples": [
        {
          "name": "allDevices",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244328",
            "data": null
          }
        },
        {
          "name": "specifiedDevices",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244328",
            "data": [
              "deviceId"
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeAllRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "array",
              "null"
            ],
            "default": null,
            "description": "设备 ID 列表。为 null 或省略时表示订阅当前权限范围内全部设备数据，并清理此前的设备级订阅。\ndata 不为空时会取消“订阅所有设备”状态并追加这些设备级订阅，但不会自动清理此前已追加的其他设备级订阅。\n若使用受限 API AccessToken，data 为空数组可能返回 code=0 但不建立有效订阅；订阅权限范围内全部设备时建议传 null 或省略 data。\n若需要缩小或替换设备级订阅范围，应先用 UnsubscribeAllRequest 取消不再需要的设备。\n若需要清理当前连接全部订阅，应发送 data 为空数组或不传的 UnsubscribeAllRequest。\n若当前账号或 Token 权限范围内没有可访问设备，服务端可能返回 code=0 但不会产生后续推送。\n同一连接内，SubscribeAllRequest 会覆盖并清理此前通过 SubscribeTraitValueRequest 建立的 Trait 订阅。\n若需从全部设备或指定设备订阅切换回仅 Trait 维度订阅，应先发送 UnsubscribeAllRequest 清理全量/设备级订阅。\n",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "SubscribeAllResponse": {
      "name": "SubscribeAllResponse",
      "title": "订阅全部/部分设备响应",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeAllResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "UnsubscribeAllRequest": {
      "name": "UnsubscribeAllRequest",
      "title": "取消订阅全部/部分设备请求",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeAllRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "array",
              "null"
            ],
            "default": null,
            "description": "设备 ID 列表。为空或 null 时表示取消全部订阅。\n若当前为全部设备订阅，按特定设备取消订阅不会生效，需传空值取消全部订阅。\n同一连接内，UnsubscribeAllRequest 会同时清理此前通过 SubscribeTraitValueRequest 建立的 Trait 订阅。\n按特定设备取消订阅只取消设备级订阅，不等同于关闭当前连接的全部推送。\n",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "UnsubscribeAllResponse": {
      "name": "UnsubscribeAllResponse",
      "title": "取消订阅全部/部分设备响应",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeAllResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "SubscribeTraitValueRequest": {
      "name": "SubscribeTraitValueRequest",
      "title": "订阅指定 Trait 值请求",
      "examples": [
        {
          "name": "subscribeTrait",
          "payload": {
            "type": "SubscribeTraitValueRequest",
            "version": "v1",
            "msgId": "get_devices_1751609244328",
            "data": [
              {
                "deviceId": "57190441014857",
                "endpointId": 3,
                "functionCode": "MediaPlayback",
                "traitCodes": [
                  "TargetPlaybackState"
                ]
              }
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeTraitValueRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "description": "需要订阅的 Trait 列表。建议传非空数组；省略 data 会解析失败。\n当前实现对空数组或 traitCodes 为空数组仍可能返回成功响应，但不会创建有效的 TraitValueUpdate 订阅。\n",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCodes"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "设备 ID。"
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "端点 ID。"
                },
                "functionCode": {
                  "type": "string",
                  "description": "功能代码。"
                },
                "traitCodes": {
                  "type": "array",
                  "description": "Trait 功能点代码列表。建议传非空数组；为空数组时不会创建或取消具体 Trait 订阅，但当前实现仍可能返回成功响应。",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "SubscribeTraitValueResponse": {
      "name": "SubscribeTraitValueResponse",
      "title": "订阅指定 Trait 值响应",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeTraitValueResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "UnsubscribeTraitValueRequest": {
      "name": "UnsubscribeTraitValueRequest",
      "title": "取消订阅指定 Trait 值请求",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeTraitValueRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "default": [],
            "description": "需要取消订阅的 Trait 列表。建议传非空数组。\n省略 data、传空数组或 traitCodes 为空数组不会取消任何 Trait 订阅，但当前实现仍可能返回成功响应。\n",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCodes"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "设备 ID。"
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "端点 ID。"
                },
                "functionCode": {
                  "type": "string",
                  "description": "功能代码。"
                },
                "traitCodes": {
                  "type": "array",
                  "description": "Trait 功能点代码列表。建议传非空数组；为空数组时不会创建或取消具体 Trait 订阅，但当前实现仍可能返回成功响应。",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "UnsubscribeTraitValueResponse": {
      "name": "UnsubscribeTraitValueResponse",
      "title": "取消订阅指定 Trait 值响应",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeTraitValueResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "TraitValueUpdate": {
      "name": "TraitValueUpdate",
      "title": "Trait 值变化推送",
      "examples": [
        {
          "name": "traitValueUpdate",
          "payload": {
            "type": "TraitValueUpdate",
            "version": "v1",
            "msgId": "1754469720110",
            "data": [
              {
                "deviceId": "57190441014857",
                "endpointId": 3,
                "functionCode": "MediaPlayback",
                "traitCode": "TargetPlaybackState",
                "value": "0",
                "time": 1754469720110
              }
            ],
            "code": 0,
            "message": ""
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TraitValueUpdate"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCode",
                "time"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "设备 ID。"
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "端点 ID。"
                },
                "functionCode": {
                  "type": "string",
                  "description": "功能代码。"
                },
                "traitCode": {
                  "type": "string",
                  "description": "Trait 功能点代码。"
                },
                "value": {
                  "description": "Trait 功能点值，类型由具体功能点定义决定。"
                },
                "time": {
                  "type": "integer",
                  "format": "int64",
                  "description": "上报时间戳，单位毫秒。"
                }
              }
            }
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "ObjectEvent": {
      "name": "objectEvent",
      "title": "对象事件推送",
      "summary": "对象事件按连接级推送注册发送；客户端应按 eventType 和 objectId 自行分发与过滤。",
      "description": "对象事件按当前连接的推送注册状态推送，不按 objectId、设备 ID 或 Trait 订阅条件做精确过滤。\n即使某些订阅请求未形成有效的 TraitValueUpdate 订阅，当前连接仍可能收到对象事件。\n若不希望当前连接继续收到任何推送，应发送 data 为空数组或不传的 UnsubscribeAllRequest，或直接关闭 WebSocket 连接。\n",
      "examples": [
        {
          "name": "deviceAdded",
          "payload": {
            "type": "objectEvent",
            "version": "v1",
            "msgId": "2",
            "data": {
              "eventType": "DEVICE_ADDED",
              "objectId": "14d3b91",
              "time": 1754469720110,
              "data": {
                "deviceId": "14d3b91",
                "name": "",
                "deviceTypesList": [
                  "Light"
                ],
                "endpointIds": [
                  0,
                  2,
                  3
                ],
                "time": 1754469720110
              }
            },
            "code": 0,
            "message": "success"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "objectEvent"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "object",
            "required": [
              "eventType",
              "objectId",
              "time"
            ],
            "properties": {
              "eventType": {
                "type": "string",
                "description": "对象事件类型。",
                "enum": [
                  "DEVICE_ADDED",
                  "DEVICE_REMOVED",
                  "DEVICE_ENDPOINT_ADDED",
                  "DEVICE_ENDPOINT_REMOVED",
                  "DEVICE_TRAIT_PARAMETER_UPDATE"
                ]
              },
              "objectId": {
                "type": "string",
                "description": "对象 ID，设备事件场景通常为设备 ID。"
              },
              "time": {
                "type": "integer",
                "format": "int64",
                "description": "事件发生时间戳，单位毫秒。"
              },
              "data": {
                "description": "根据 eventType 判断具体结构。",
                "type": [
                  "object",
                  "null"
                ],
                "additionalProperties": true
              }
            }
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，0 表示成功，非 0 表示失败。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    },
    "ErrorMessage": {
      "name": "ErrorMessage",
      "title": "错误响应",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ErrorMessage"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "消息唯一标识。正常请求和响应使用相同 msgId 关联；解析失败、部分权限或内部异常可能返回 UNKNOWN；服务端推送由服务端生成，不等同于订阅请求 msgId。",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ]
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "处理结果码，非 0 表示失败；不建议客户端依赖某个具体错误码判断固定业务场景。"
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "处理结果描述。"
          }
        }
      }
    }
  }
} satisfies PlaygroundSpec;

export default aqaraLifeWebSocketSpecZh;
