/* eslint-disable */
// This file is autogenerated by scripts/generate-asyncapi-playground-specs.mjs
import type { PlaygroundSpec } from "./types";

const aqaraLifeWebSocketSpecEn = {
  "title": "Studio WebSocket API",
  "version": "v1",
  "description": "This document describes the asynchronous messages exchanged between the client and the Studio WebSocket service:\n- The client sends authentication, heartbeat, subscribe, and unsubscribe requests.\n- Studio returns responses to requests and proactively pushes messages when subscriptions match or device events occur.\n- This contract covers device, Trait, and object-event subscriptions, but does not cover standalone alarm-event subscriptions such as SubscribeEventRequest and UnsubscribeEventRequest.\n- For the Studio self-domain endpoint and LAN Studio environments, if the token is not included during the handshake, `AuthRequest` may be sent as the first message after the connection is established.\n\nPerspective note: this AsyncAPI describes the integration behavior that client applications need to implement; `send` means the client sends to Studio, and `receive` means the client receives from Studio.\n",
  "servers": [
    {
      "id": "lanStudio",
      "label": "lanStudio",
      "description": "LAN Studio WebSocket service, for local connections only; the address is provided by deployment configuration or service discovery and must not be used for production or cloud connections.",
      "protocol": "ws",
      "hostDefault": "{localStudioEndpoint}",
      "pathname": "/open/ws"
    }
  ],
  "operations": [
    {
      "id": "sendAuthRequest",
      "action": "send",
      "messages": [
        "AuthRequest"
      ]
    },
    {
      "id": "receiveAuthResponse",
      "action": "receive",
      "messages": [
        "AuthResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "sendPing",
      "action": "send",
      "messages": [
        "PingRequest"
      ]
    },
    {
      "id": "receivePong",
      "action": "receive",
      "messages": [
        "PongResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "sendSubscriptionCommand",
      "action": "send",
      "messages": [
        "SubscribeAllRequest",
        "UnsubscribeAllRequest",
        "SubscribeTraitValueRequest",
        "UnsubscribeTraitValueRequest",
        "SubscribeObjectEventRequest",
        "UnsubscribeObjectEventRequest"
      ]
    },
    {
      "id": "receiveSubscriptionCommandResponse",
      "action": "receive",
      "messages": [
        "SubscribeAllResponse",
        "UnsubscribeAllResponse",
        "SubscribeTraitValueResponse",
        "UnsubscribeTraitValueResponse",
        "SubscribeObjectEventResponse",
        "UnsubscribeObjectEventResponse",
        "ErrorMessage"
      ]
    },
    {
      "id": "receivePushMessage",
      "action": "receive",
      "messages": [
        "TraitValueUpdate",
        "ObjectEvent",
        "ErrorMessage"
      ]
    }
  ],
  "messages": {
    "AuthRequest": {
      "name": "AuthRequest",
      "title": "WebSocket authentication request",
      "summary": "First-message authentication flow for the Studio self-domain endpoint and LAN Studio environments; not used in production or cloud environments.",
      "examples": [
        {
          "name": "bearerToken",
          "payload": {
            "type": "AuthRequest",
            "version": "v1",
            "msgId": "10001",
            "data": {
              "authType": "token",
              "token": "<accessToken>",
              "deviceUniqueId": "<deviceUniqueId>",
              "clientId": "<clientId>"
            }
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "AuthRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "object",
            "required": [
              "token"
            ],
            "properties": {
              "authType": {
                "type": "string",
                "description": "Authentication type. Pass `token`.",
                "enum": [
                  "token"
                ],
                "default": "token"
              },
              "token": {
                "type": "string",
                "description": "Use the format `Bearer <Token>`, where `<Token>` is the raw token obtained from Aqara Studio. Do not log or expose this token."
              }
            }
          }
        }
      }
    },
    "AuthResponse": {
      "name": "AuthResponse",
      "title": "WebSocket authentication response",
      "examples": [
        {
          "name": "success",
          "payload": {
            "type": "AuthResponse",
            "version": "v1",
            "msgId": "10001",
            "data": "",
            "code": 0,
            "message": "Authentication successful. Welcome <username>"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "AuthResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "PingRequest": {
      "name": "ping",
      "title": "Heartbeat request",
      "examples": [
        {
          "name": "ping",
          "payload": {
            "type": "ping",
            "version": "v1",
            "msgId": "10002",
            "data": null
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ping"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": null
          }
        }
      }
    },
    "PongResponse": {
      "name": "pong",
      "title": "Heartbeat response",
      "examples": [
        {
          "name": "pong",
          "payload": {
            "type": "pong",
            "version": "v1",
            "msgId": "10002",
            "data": "pong",
            "code": 0,
            "message": "success"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "pong"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "string",
            "enum": [
              "pong"
            ]
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "SubscribeAllRequest": {
      "name": "SubscribeAllRequest",
      "title": "Subscribe to all or selected devices request",
      "examples": [
        {
          "name": "allDevices",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244328",
            "data": null
          }
        },
        {
          "name": "allDevicesWithEmptyArray",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244329",
            "data": []
          }
        },
        {
          "name": "specifiedDevices",
          "payload": {
            "type": "SubscribeAllRequest",
            "version": "v1",
            "msgId": "1751609244328",
            "data": [
              "deviceId"
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeAllRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "array",
              "null"
            ],
            "default": null,
            "description": "List of device IDs. When null, omitted, or an empty array, this subscribes to all device data within the current permission scope and clears previously established device-level subscriptions.\nWhen `data` is non-empty, the “subscribe all devices” state is cancelled and these device-level subscriptions are appended, but previously appended device-level subscriptions are not automatically cleared.\nTo narrow or replace the device-level subscription scope, first use UnsubscribeAllRequest to remove devices that are no longer needed.\nTo clear all device-data and Trait subscriptions on the current connection, send UnsubscribeAllRequest with an empty data array or omit data; this request does not clear standalone event or object-event subscriptions.\nIf the current account or token permission scope has no accessible devices, the server may return code=0 but no subsequent push messages will be generated.\nWithin the same connection, SubscribeAllRequest overrides and clears Trait subscriptions previously established via SubscribeTraitValueRequest.\nTo switch from all-device or selected-device subscriptions back to Trait-only subscriptions, first send UnsubscribeAllRequest to clear the all-device/device-level subscriptions.\n",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "SubscribeAllResponse": {
      "name": "SubscribeAllResponse",
      "title": "Subscribe to all or selected devices response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeAllResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "UnsubscribeAllRequest": {
      "name": "UnsubscribeAllRequest",
      "title": "Unsubscribe from all or selected devices request",
      "description": "Clears subscriptions for all or selected device data and also clears Trait subscriptions for the current session.\nIt does not clear standalone event subscriptions or precise object-event subscriptions, and it does not disable the default DEVICE_ADDED and DEVICE_REMOVED events received on authenticated connections.\n",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeAllRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "array",
              "null"
            ],
            "default": null,
            "description": "List of device IDs. Empty or null means unsubscribe from all device-data and Trait subscriptions.\nIf the current connection is subscribed to all devices, unsubscribing by specific device IDs has no effect; an empty value must be passed to cancel all device-data subscriptions.\nWithin the same connection, UnsubscribeAllRequest also clears Trait subscriptions previously established via SubscribeTraitValueRequest.\nUnsubscribing specific devices only removes device-level subscriptions and does not mean stopping all push messages on the current connection.\nThis request does not clear rules established by SubscribeEventRequest or SubscribeObjectEventRequest, nor does it disable the default DEVICE_ADDED and DEVICE_REMOVED push messages.\n",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "UnsubscribeAllResponse": {
      "name": "UnsubscribeAllResponse",
      "title": "Unsubscribe from all or selected devices response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeAllResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "SubscribeTraitValueRequest": {
      "name": "SubscribeTraitValueRequest",
      "title": "Subscribe to specified Trait values request",
      "examples": [
        {
          "name": "subscribeTrait",
          "payload": {
            "type": "SubscribeTraitValueRequest",
            "version": "v1",
            "msgId": "get_devices_1751609244328",
            "data": [
              {
                "deviceId": "57190441014857",
                "endpointId": 3,
                "functionCode": "MediaPlayback",
                "traitCodes": [
                  "TargetPlaybackState"
                ]
              }
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeTraitValueRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "description": "List of Traits to subscribe to. A non-empty array is recommended; omitting data causes parsing to fail.\nIn the current implementation, an empty array or empty traitCodes may still return a success response, but no effective TraitValueUpdate subscription will be created.\n",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCodes"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "Device ID."
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "Endpoint ID."
                },
                "functionCode": {
                  "type": "string",
                  "description": "Function code."
                },
                "traitCodes": {
                  "type": "array",
                  "description": "List of Trait feature point codes. A non-empty array is recommended; an empty array does not create or cancel any specific Trait subscriptions, although the current implementation may still return a success response.",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "SubscribeTraitValueResponse": {
      "name": "SubscribeTraitValueResponse",
      "title": "Subscribe to specified Trait values response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeTraitValueResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "UnsubscribeTraitValueRequest": {
      "name": "UnsubscribeTraitValueRequest",
      "title": "Unsubscribe from specified Trait values request",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeTraitValueRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "default": [],
            "description": "List of Traits to unsubscribe from. A non-empty array is recommended.\nOmitting data, passing an empty array, or using empty traitCodes will not cancel any Trait subscriptions, although the current implementation may still return a success response.\n",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCodes"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "Device ID."
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "Endpoint ID."
                },
                "functionCode": {
                  "type": "string",
                  "description": "Function code."
                },
                "traitCodes": {
                  "type": "array",
                  "description": "List of Trait feature point codes. A non-empty array is recommended; an empty array does not create or cancel any specific Trait subscriptions, although the current implementation may still return a success response.",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "UnsubscribeTraitValueResponse": {
      "name": "UnsubscribeTraitValueResponse",
      "title": "Unsubscribe from specified Trait values response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeTraitValueResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "SubscribeObjectEventRequest": {
      "name": "SubscribeObjectEventRequest",
      "title": "Subscribe to space, device-space relationship, and automation object events",
      "summary": "Incrementally adds object-event subscriptions for the current WebSocket session; duplicate subscriptions are idempotent.",
      "description": "When `objectIds` is omitted, null, or an empty array, subscribe to all currently accessible objects under the specified `eventTypes`; when non-empty, subscribe only to the specified objects.\nSubsequent subscription requests are merged with existing rules and do not overwrite previously specified object rules. Subscribing to all objects replaces the existing ID list for the same event type.\nApps may use all-object subscriptions to maintain a complete list; screen devices and third-party services typically subscribe to specified objects according to their business scope.\n",
      "examples": [
        {
          "name": "subscribeAllPreciseObjectEvents",
          "payload": {
            "type": "SubscribeObjectEventRequest",
            "version": "v1",
            "msgId": "object-subscribe-1",
            "data": [
              {
                "eventTypes": [
                  "SPACE_ADDED",
                  "SPACE_REMOVED",
                  "SPACE_UPDATED",
                  "AUTOMATION_ADDED",
                  "AUTOMATION_REMOVED",
                  "AUTOMATION_UPDATED",
                  "AUTOMATION_SPACE_UPDATED",
                  "DEVICE_SPACE_UPDATED"
                ],
                "objectIds": []
              }
            ]
          }
        },
        {
          "name": "subscribeSelectedObjects",
          "payload": {
            "type": "SubscribeObjectEventRequest",
            "version": "v1",
            "msgId": "object-subscribe-2",
            "data": [
              {
                "eventTypes": [
                  "DEVICE_SPACE_UPDATED"
                ],
                "objectIds": [
                  "device-1",
                  "device-2"
                ]
              },
              {
                "eventTypes": [
                  "AUTOMATION_REMOVED",
                  "AUTOMATION_UPDATED",
                  "AUTOMATION_SPACE_UPDATED"
                ],
                "objectIds": [
                  "automation-1"
                ]
              }
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeObjectEventRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "minItems": 1,
            "maxItems": 100,
            "items": {
              "type": "object",
              "required": [
                "eventTypes"
              ],
              "properties": {
                "eventTypes": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "type": "string",
                    "enum": [
                      "DEVICE_SPACE_UPDATED",
                      "SPACE_ADDED",
                      "SPACE_REMOVED",
                      "SPACE_UPDATED",
                      "AUTOMATION_ADDED",
                      "AUTOMATION_REMOVED",
                      "AUTOMATION_UPDATED",
                      "AUTOMATION_SPACE_UPDATED"
                    ]
                  }
                },
                "objectIds": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "maxItems": 1000,
                  "uniqueItems": true,
                  "items": {
                    "type": "string",
                    "minLength": 1
                  },
                  "description": "When subscribing, omitted, null, or empty objectIds means all objects within the current permission scope; when non-empty, only the specified objects are matched.\nWhen unsubscribing, omitted, null, or empty objectIds means clearing all rules for the corresponding eventTypes; when non-empty, only the specified objects are removed.\nWithin the same WebSocket session, at most 1000 distinct objectIds may be cumulatively subscribed under each eventType.\nWhen objectIds is non-empty, the eventTypes in the same item must belong to the same object type; SPACE_ADDED and AUTOMATION_ADDED support only the all-objects semantic.\nThe protocol does not use a scope field; the all-objects semantic is represented uniformly through objectIds.\n"
                }
              }
            },
            "description": "Must contain 1 to 100 subscription items. Requests are merged incrementally by session, and duplicate subscriptions are idempotent.\nSPACE_ADDED and AUTOMATION_ADDED only allow the all-objects semantic for objectIds.\n"
          }
        }
      }
    },
    "SubscribeObjectEventResponse": {
      "name": "SubscribeObjectEventResponse",
      "title": "Object-event subscription response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "SubscribeObjectEventResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "UnsubscribeObjectEventRequest": {
      "name": "UnsubscribeObjectEventRequest",
      "title": "Unsubscribe from space, device-space relationship, and automation object events",
      "summary": "Removes specified object rules or clears specified event types for the current WebSocket session.",
      "description": "When `objectIds` is non-empty, only the specified objects are removed; when omitted, null, or an empty array, all object rules for the corresponding `eventTypes` are cleared.\nAll-object subscriptions do not support excluding selected objects. To switch from all objects to specified objects, first clear the event type and then send a new specified-object subscription.\n",
      "examples": [
        {
          "name": "unsubscribeSelectedObject",
          "payload": {
            "type": "UnsubscribeObjectEventRequest",
            "version": "v1",
            "msgId": "object-unsubscribe-1",
            "data": [
              {
                "eventTypes": [
                  "AUTOMATION_UPDATED"
                ],
                "objectIds": [
                  "automation-1"
                ]
              }
            ]
          }
        },
        {
          "name": "clearEventType",
          "payload": {
            "type": "UnsubscribeObjectEventRequest",
            "version": "v1",
            "msgId": "object-unsubscribe-2",
            "data": [
              {
                "eventTypes": [
                  "AUTOMATION_UPDATED"
                ],
                "objectIds": []
              }
            ]
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeObjectEventRequest"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "minItems": 1,
            "maxItems": 100,
            "items": {
              "type": "object",
              "required": [
                "eventTypes"
              ],
              "properties": {
                "eventTypes": {
                  "type": "array",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "type": "string",
                    "enum": [
                      "DEVICE_SPACE_UPDATED",
                      "SPACE_ADDED",
                      "SPACE_REMOVED",
                      "SPACE_UPDATED",
                      "AUTOMATION_ADDED",
                      "AUTOMATION_REMOVED",
                      "AUTOMATION_UPDATED",
                      "AUTOMATION_SPACE_UPDATED"
                    ]
                  }
                },
                "objectIds": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "maxItems": 1000,
                  "uniqueItems": true,
                  "items": {
                    "type": "string",
                    "minLength": 1
                  },
                  "description": "When subscribing, omitted, null, or empty objectIds means all objects within the current permission scope; when non-empty, only the specified objects are matched.\nWhen unsubscribing, omitted, null, or empty objectIds means clearing all rules for the corresponding eventTypes; when non-empty, only the specified objects are removed.\nWithin the same WebSocket session, at most 1000 distinct objectIds may be cumulatively subscribed under each eventType.\nWhen objectIds is non-empty, the eventTypes in the same item must belong to the same object type; SPACE_ADDED and AUTOMATION_ADDED support only the all-objects semantic.\nThe protocol does not use a scope field; the all-objects semantic is represented uniformly through objectIds.\n"
                }
              }
            },
            "description": "Must contain 1 to 100 unsubscribe items; an empty array is a parameter error and does not mean unsubscribing from all event types.\nWhen objectIds is omitted, null, or an empty array, all object rules under the corresponding eventTypes for the current session are removed; when non-empty, only the specified objects are removed.\n"
          }
        }
      }
    },
    "UnsubscribeObjectEventResponse": {
      "name": "UnsubscribeObjectEventResponse",
      "title": "Object-event unsubscription response",
      "examples": [],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "UnsubscribeObjectEventResponse"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "default": ""
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "TraitValueUpdate": {
      "name": "TraitValueUpdate",
      "title": "Trait value change push",
      "examples": [
        {
          "name": "traitValueUpdate",
          "payload": {
            "type": "TraitValueUpdate",
            "version": "v1",
            "msgId": "1754469720110",
            "data": [
              {
                "deviceId": "57190441014857",
                "endpointId": 3,
                "functionCode": "MediaPlayback",
                "traitCode": "TargetPlaybackState",
                "value": "0",
                "time": 1754469720110
              }
            ],
            "code": 0,
            "message": ""
          }
        },
        {
          "name": "deviceNameUpdated",
          "payload": {
            "type": "TraitValueUpdate",
            "version": "v1",
            "msgId": "1789113600000",
            "data": [
              {
                "deviceId": "device-1",
                "endpointId": 0,
                "functionCode": "EndpointLabel",
                "traitCode": "EndpointName",
                "value": "Living Room Light",
                "time": 1789113600000
              }
            ],
            "code": 0,
            "message": ""
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "TraitValueUpdate"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "deviceId",
                "endpointId",
                "functionCode",
                "traitCode",
                "time"
              ],
              "properties": {
                "deviceId": {
                  "type": "string",
                  "description": "Device ID."
                },
                "endpointId": {
                  "type": "integer",
                  "format": "int32",
                  "description": "Endpoint ID."
                },
                "functionCode": {
                  "type": "string",
                  "description": "Function code."
                },
                "traitCode": {
                  "type": "string",
                  "description": "Trait feature point code."
                },
                "value": {
                  "description": "Trait feature point value. The actual type is determined by the specific feature point definition."
                },
                "time": {
                  "type": "integer",
                  "format": "int64",
                  "description": "Report timestamp in milliseconds."
                }
              }
            }
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "ObjectEvent": {
      "name": "objectEvent",
      "title": "Object event push",
      "summary": "Device add/remove events are pushed by default; changes to spaces, automations, and space relationships are delivered according to precise object subscriptions.",
      "description": "DEVICE_ADDED and DEVICE_REMOVED are pushed by default after an authenticated connection is established.\nSPACE_*, AUTOMATION_*, and DEVICE_SPACE_UPDATED are delivered only to SubscribeObjectEventRequest sessions that match the eventType, objectId, and current permissions.\nDEVICE_ENDPOINT_* and DEVICE_TRAIT_PARAMETER_UPDATE continue to follow the existing device-data subscriptions.\nScenes are represented by the `manualTriggers` inside an automation; no standalone scene event is provided, and changes in count do not produce separate events.\nThe protocol does not provide a globally unique event ID; the push `msgId` is only for link tracing. Callers should process events idempotently according to object state rather than deduplicating only by `objectId`, `eventType`, and `time`.\n",
      "examples": [
        {
          "name": "deviceAdded",
          "payload": {
            "type": "objectEvent",
            "version": "v1",
            "msgId": "2",
            "data": {
              "eventType": "DEVICE_ADDED",
              "objectId": "14d3b91",
              "time": 1754469720110,
              "data": {
                "deviceId": "14d3b91",
                "name": "",
                "deviceTypesList": [
                  "Light"
                ],
                "endpointIds": [
                  0,
                  2,
                  3
                ],
                "time": 1754469720110
              }
            },
            "code": 0,
            "message": "success"
          }
        },
        {
          "name": "deviceSpaceUpdated",
          "payload": {
            "type": "objectEvent",
            "version": "v1",
            "msgId": "object-event-1",
            "data": {
              "eventType": "DEVICE_SPACE_UPDATED",
              "objectId": "device-1",
              "time": 1789113600000,
              "data": {
                "deviceId": "device-1",
                "oldSpaceId": "space-1",
                "space": {
                  "spaceId": "space-2",
                  "name": "Bedroom",
                  "spatialMarking": "room",
                  "parentSpaceId": "home-1"
                }
              }
            },
            "code": 0,
            "message": "success"
          }
        },
        {
          "name": "automationUpdated",
          "payload": {
            "type": "objectEvent",
            "version": "v1",
            "msgId": "object-event-2",
            "data": {
              "eventType": "AUTOMATION_UPDATED",
              "objectId": "automation-1",
              "time": 1789113600000,
              "data": {
                "automationId": "automation-1",
                "definitionType": "WHEN_IF_THEN",
                "name": "Home Mode",
                "enabled": true,
                "createTime": 1789000000000,
                "manualTriggers": [
                  {
                    "triggerNodeId": "manual-trigger-1",
                    "triggerName": "Home"
                  }
                ]
              }
            },
            "code": 0,
            "message": "success"
          }
        },
        {
          "name": "automationSpaceUnassigned",
          "payload": {
            "type": "objectEvent",
            "version": "v1",
            "msgId": "object-event-3",
            "data": {
              "eventType": "AUTOMATION_SPACE_UPDATED",
              "objectId": "automation-1",
              "time": 1789113600000,
              "data": {
                "automationId": "automation-1",
                "oldSpaceId": "space-2",
                "space": null
              }
            },
            "code": 0,
            "message": "success"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "data",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "objectEvent"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "A non-empty identifier used by the request. It should remain unique at least among unfinished requests on the current connection. Normal responses correlate with the same msgId, while msgIds on server push messages are used only for link tracing, do not correspond to subscription request msgIds, and are not guaranteed to be globally unique.",
            "minLength": 1,
            "maxLength": 64
          },
          "data": {
            "if": {
              "properties": {
                "eventType": {
                  "enum": [
                    "AUTOMATION_SPACE_UPDATED"
                  ]
                }
              }
            },
            "then": {
              "required": [
                "data"
              ],
              "properties": {
                "data": {
                  "type": "object",
                  "required": [
                    "automationId",
                    "oldSpaceId",
                    "space"
                  ],
                  "properties": {
                    "automationId": {
                      "type": "string",
                      "description": "Automation ID."
                    },
                    "oldSpaceId": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "description": "Space ID before the change; null when associated for the first time."
                    },
                    "space": {
                      "anyOf": [
                        {
                          "type": "object",
                          "description": "Latest space summary. The client should maintain a unified space cache by `spaceId` to avoid repeatedly storing potentially stale names, markings, and parent relationships in device or automation relationship data; `parentSpaceId` indicates the parent space of the summary, and is null for a root space.",
                          "required": [
                            "spaceId",
                            "name",
                            "parentSpaceId"
                          ],
                          "properties": {
                            "spaceId": {
                              "type": "string",
                              "description": "Space ID."
                            },
                            "name": {
                              "type": "string",
                              "description": "Space name."
                            },
                            "spatialMarking": {
                              "type": [
                                "string",
                                "null"
                              ],
                              "description": "Space marking; null when no marking exists."
                            },
                            "parentSpaceId": {
                              "type": [
                                "string",
                                "null"
                              ],
                              "description": "Parent space ID of the space; null for a root space. For SPACE_ADDED and SPACE_UPDATED this is the parent space after the event; for SPACE_REMOVED it is the parent space before deletion."
                            }
                          }
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Space summary at the time the relationship changes; null when the relationship is removed. Read the space ID from `space.spaceId`; subsequent name, marking, or parent changes should update a unified space cache via SPACE_UPDATED. This relationship also applies to scenes inside the automation."
                    }
                  }
                }
              }
            }
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. 0 indicates success, and any non-zero value indicates failure."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Processing result message."
          }
        }
      }
    },
    "ErrorMessage": {
      "name": "ErrorMessage",
      "title": "Error response",
      "examples": [
        {
          "name": "missingMsgId",
          "payload": {
            "type": "ErrorMessage",
            "version": "v1",
            "msgId": "",
            "data": null,
            "code": 400,
            "message": "Missing msgId"
          }
        }
      ],
      "payloadSchema": {
        "type": "object",
        "required": [
          "type",
          "version",
          "msgId",
          "code",
          "message"
        ],
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ErrorMessage"
            ]
          },
          "version": {
            "type": "string",
            "enum": [
              "v1"
            ]
          },
          "msgId": {
            "type": "string",
            "description": "Returns the original request msgId when it can be correlated; the server may return UNKNOWN or an empty string when it cannot correlate the original request.",
            "minLength": 0,
            "maxLength": 64
          },
          "data": {
            "type": [
              "string",
              "null"
            ],
            "description": "Error responses typically do not carry business data."
          },
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Processing result code. Any non-zero value indicates failure; clients are discouraged from relying on specific error codes for fixed business logic decisions."
          },
          "message": {
            "type": [
              "string",
              "null"
            ],
            "description": "Error message."
          }
        }
      }
    }
  }
} satisfies PlaygroundSpec;

export default aqaraLifeWebSocketSpecEn;
